# Sales & Revenue Analysis Dashboard

## Thiranex Internship Project

### Objective
The objective of this project is to analyze sales and revenue data,
track important business KPIs, identify top-performing products and
customers, analyze monthly sales trends, and generate useful business insights.

### Tools Used
- Python
- Pandas
- Matplotlib
- Plotly
- Google Colab

### Project Type
Sales and Revenue Analysis

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px
import ipywidgets as widgets
from IPython.display import display

print("Libraries imported successfully!")

Libraries imported successfully!


In [ ]:
# Sales by Category
category_data = pd.DataFrame({
    "Category": [
        "Technology",
        "Office Supplies",
        "Other",
        "Furniture"
    ],
    "Sales": [
        1.30,
        0.53,
        0.33,
        0.09
    ]
})

# Sales by Month
monthly_data = pd.DataFrame({
    "Month": [
        "January",
        "February",
        "March",
        "April",
        "May",
        "June",
        "July"
    ],
    "Sales": [
        0.11,
        0.07,
        0.05,
        0.17,
        0.23,
        0.12,
        0.26
    ]
})

# Top 5 Products
product_data = pd.DataFrame({
    "Product": [
        "Power Bank Shell 5V",
        "HDMI Cable 2.0 4K",
        "Bamboo Folding Portable",
        "Transparent Face Mask",
        "Rovtop USB Gaming"
    ],
    "Sales": [
        0.34,
        0.32,
        0.27,
        0.22,
        0.14
    ]
})

# Top 5 Customers
customer_data = pd.DataFrame({
    "Customer": [
        "Xylona Preis",
        "Mona Khan",
        "Kim Larson",
        "Yoga Bobby",
        "Arianne Irving"
    ],
    "Sales": [
        0.27,
        0.20,
        0.15,
        0.13,
        0.10
    ]
})

# Profit percentage by segment
segment_data = pd.DataFrame({
    "Segment": [
        "Corporate",
        "Home Office",
        "Consumer"
    ],
    "Profit_Percentage": [
        13.44,
        19.12,
        67.44
    ]
})

print("Dashboard data created successfully!")

Dashboard data created successfully!


In [ ]:
print("SALES BY CATEGORY")
display(category_data)

print("SALES BY MONTH")
display(monthly_data)

print("TOP 5 PRODUCTS")
display(product_data)

print("TOP 5 CUSTOMERS")
display(customer_data)

print("PROFIT BY SEGMENT")
display(segment_data)

SALES BY CATEGORY


,Category,Sales
0,Technology,1.30
1,Office Supplies,0.53
2,Other,0.33
3,Furniture,0.09


SALES BY MONTH


,Month,Sales
0,January,0.11
1,February,0.07
2,March,0.05
3,April,0.17
4,May,0.23
5,June,0.12
6,July,0.26


TOP 5 PRODUCTS


,Product,Sales
0,Power Bank Shell 5V,0.34
1,HDMI Cable 2.0 4K,0.32
2,Bamboo Folding Portable,0.27
3,Transparent Face Mask,0.22
4,Rovtop USB Gaming,0.14


TOP 5 CUSTOMERS


,Customer,Sales
0,Xylona Preis,0.27
1,Mona Khan,0.20
2,Kim Larson,0.15
3,Yoga Bobby,0.13
4,Arianne Irving,0.10


PROFIT BY SEGMENT


,Segment,Profit_Percentage
0,Corporate,13.44
1,Home Office,19.12
2,Consumer,67.44


In [ ]:
total_customers = 116
total_orders = 171
total_quantity = 23000
total_sales = 2.25
total_profit = 1.01

print("========== KEY PERFORMANCE INDICATORS ==========")
print("Total Customers :", total_customers)
print("Total Orders    :", total_orders)
print("Total Quantity  :", total_quantity)
print("Total Sales     :", str(total_sales) + " Million")
print("Total Profit    :", str(total_profit) + " Million")

========== KEY PERFORMANCE INDICATORS ==========
Total Customers : 116
Total Orders    : 171
Total Quantity  : 23000
Total Sales     : 2.25 Million
Total Profit    : 1.01 Million


In [ ]:
fig = px.bar(
    category_data,
    x="Category",
    y="Sales",
    title="Sales by Category",
    text="Sales"
)

fig.update_traces(texttemplate="%{text:.2f}M", textposition="outside")

fig.show()

In [ ]:
fig = px.line(
    monthly_data,
    x="Month",
    y="Sales",
    markers=True,
    title="Monthly Sales Trend"
)

fig.update_traces(text=monthly_data["Sales"])

fig.show()

In [ ]:
fig = px.bar(
    product_data,
    x="Sales",
    y="Product",
    orientation="h",
    title="Top 5 Products by Sales",
    text="Sales"
)

fig.update_traces(texttemplate="%{text:.2f}M", textposition="outside")

fig.show()

In [ ]:
fig = px.bar(
    customer_data,
    x="Sales",
    y="Customer",
    orientation="h",
    title="Top 5 Customers by Sales",
    text="Sales"
)

fig.update_traces(texttemplate="%{text:.2f}M", textposition="outside")

fig.show()

In [ ]:
fig = px.pie(
    segment_data,
    names="Segment",
    values="Profit_Percentage",
    title="Profit Percentage by Segment",
    hole=0.4
)

fig.show()

In [ ]:
category_dropdown = widgets.Dropdown(
    options=["All"] + list(category_data["Category"]),
    description="Category:"
)

output = widgets.Output()

def filter_category(change):
    with output:
        output.clear_output()

        if change["new"] == "All":
            display(category_data)
        else:
            filtered = category_data[
                category_data["Category"] == change["new"]
            ]
            display(filtered)

category_dropdown.observe(filter_category, names="value")

display(category_dropdown)
display(output)

display(category_data)

Dropdown(description='Category:', options=('All', 'Technology', 'Office Supplies', 'Other', 'Furniture'), valu…

Output()

,Category,Sales
0,Technology,1.30
1,Office Supplies,0.53
2,Other,0.33
3,Furniture,0.09


In [ ]:
month_dropdown = widgets.Dropdown(
    options=["All"] + list(monthly_data["Month"]),
    description="Month:"
)

month_output = widgets.Output()

def filter_month(change):
    with month_output:
        month_output.clear_output()

        if change["new"] == "All":
            display(monthly_data)
        else:
            filtered = monthly_data[
                monthly_data["Month"] == change["new"]
            ]
            display(filtered)

month_dropdown.observe(filter_month, names="value")

display(month_dropdown)
display(month_output)

display(monthly_data)

Dropdown(description='Month:', options=('All', 'January', 'February', 'March', 'April', 'May', 'June', 'July')…

Output()

,Month,Sales
0,January,0.11
1,February,0.07
2,March,0.05
3,April,0.17
4,May,0.23
5,June,0.12
6,July,0.26


# Business Insights

1. Technology is the largest sales category, contributing approximately
   1.30 million in sales.

2. Office Supplies contributes approximately 0.53 million in sales.

3. The highest visible monthly sales value is in July, at approximately
   0.26 million.

4. May also shows strong sales of approximately 0.23 million.

5. Power Bank Shell 5V is the highest-selling product among the displayed
   top five products, with approximately 0.34 million in sales.

6. Xylona Preis is the highest-selling customer among the displayed
   top five customers, with approximately 0.27 million in sales.

7. Consumer is the largest profit segment, representing approximately
   67.44% of the displayed profit percentage.

8. The dashboard reports total sales of approximately 2.25 million and
   total profit of approximately 1.01 million.

9. The dashboard reports 116 customers and 171 orders.

10. Interactive category and month filters can help users examine the
    sales information more easily.

# Conclusion

The Sales & Revenue Analysis Dashboard provides a clear view of important
sales and business performance indicators.

The analysis includes total customers, total orders, total quantity,
total sales, total profit, monthly sales trends, category-wise sales,
top-performing products, top customers, and profit distribution by segment.

Interactive filters were also created to allow users to explore the data.

This project helped demonstrate the use of Python, Pandas and Plotly for
data analysis and visualization and improved understanding of KPI tracking
and business insight generation.

In [ ]:
category_data.to_csv("sales_by_category.csv", index=False)
monthly_data.to_csv("sales_by_month.csv", index=False)
product_data.to_csv("top_products.csv", index=False)
customer_data.to_csv("top_customers.csv", index=False)
segment_data.to_csv("profit_by_segment.csv", index=False)

print("CSV files saved successfully!")

CSV files saved successfully!


# Project Summary

## Project Name
Sales & Revenue Analysis Dashboard

## Internship
Thiranex Internship

## Objective
To analyze sales and revenue performance using KPIs, charts,
interactive filters and business insights.

## KPIs
- Total Customers: 116
- Total Orders: 171
- Total Quantity: 23K
- Total Sales: 2.25M
- Total Profit: 1.01M

## Visualizations
- Sales by Category
- Monthly Sales Trend
- Top 5 Products by Sales
- Top 5 Customers by Sales
- Profit Percentage by Segment

## Interactive Features
- Category filter
- Month filter

## Tools
- Python
- Pandas
- Plotly
- Google Colab

## Outcome
The project demonstrates data visualization, KPI tracking,
sales analysis and business insight generation.